<a href="https://colab.research.google.com/github/FrancisDcruz/Kaggle-Income_Prediction-/blob/main/Income_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [ ]:
from google.colab import files
files.upload()

In [8]:
data=pd.read_csv('/content/train.csv')

In [9]:
data['workclass'].value_counts()

Private             30587
Self-emp-not-inc     3464
Local-gov            2822
State-gov            1756
Self-emp-inc         1518
Federal-gov          1284
Without-pay            20
Never-worked            8
Name: workclass, dtype: int64

In [10]:
data=data.dropna()
data = data[data['native-country']=='United-States']
data= data.drop('native-country', axis = 1)

In [11]:
data['workclass'].value_counts()

Private             27181
Self-emp-not-inc     3146
Local-gov            2650
State-gov            1624
Self-emp-inc         1359
Federal-gov          1189
Without-pay            19
Name: workclass, dtype: int64

In [15]:
data_categorical=data.select_dtypes(include=['object']).columns
df_dummy=pd.get_dummies(data[data_categorical])
df_dummy.shape

(37168, 57)

In [16]:
num_cols = [ col for col in list(data.columns) if data[col].dtype !='object'  and  col != 'income_>50K']
num_cols

['age',
 'fnlwgt',
 'educational-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week']

In [17]:
final_data = pd.DataFrame()
final_data = pd.concat([df_dummy , data[num_cols] , data['income_>50K'] ] , axis = 1)
final_data.shape

(37168, 64)

In [18]:
x=final_data.drop(['income_>50K'],axis=1)
y=final_data['income_>50K']

In [19]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.3, random_state = 0) 

Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators =200, criterion = 'gini', max_depth=15, max_features='auto',random_state = 0)
classifier.fit(x_train, y_train)
y_pred_test = classifier.predict(x_test) 

In [21]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred_test))  

[[7882  434]
 [1223 1612]]


In [22]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred_test)
print("Accuracy for this model {} %".format(acc*100))

Accuracy for this model 85.14034615729531 %


In [23]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x= sc.fit_transform(x_train)

SVM

In [ ]:
parameters=[{'C':[1,10,100,1000],'kernel':['linear']},
            {'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
classifier= SVC()
grid_search=GridSearchCV(estimator=classifier,
                         param_grid=parameters,
                         scoring='accuracy',
                         cv=10,
                         n_jobs=-1)
grid_search=grid_search.fit(x_train,y_train)

SVM


In [25]:
from sklearn.svm import SVC
classifier1= SVC()
classifier1.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
y_pred_test1 = classifier1.predict(x_test)  
print(y_pred_test1)

[0 0 0 ... 0 0 0]


In [27]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred_test1)) 

[[8307    9]
 [2416  419]]


In [28]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred_test1)
print("Accuracy for this model {} %".format(acc*100))

Accuracy for this model 78.25307147341046 %
